# Generated by Django 2.2.6 on 2019-10-15 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cinema',
            old_name='cidade',
            new_name='city',
        ),
        migrations.AddField(
            model_name='cinema',
            name='alt_name',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cinema',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
