# Generated by Django 2.2.6 on 2019-10-16 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0002_auto_20191015_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='banner',
        ),
        migrations.AddField(
            model_name='movie',
            name='banner_url',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='cinema',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='scrapper.Cinema'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='purchase_link',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='room',
            field=models.IntegerField(default=''),
            preserve_default=False,
        ),
    ]
