# Generated by Django 2.2.6 on 2019-11-08 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0002_auto_20191016_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='session',
            name='technology',
        ),
    ]
