# Generated by Django 3.0 on 2020-01-03 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0005_session_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='imdb_rating',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
