# Generated by Django 3.0 on 2020-01-03 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0006_movie_imdb_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='imdb_rating',
            field=models.CharField(max_length=4),
        ),
    ]
